export type category = { key: string; label: string }
export const categories: category[] = [
    { key: "appetizers", label: "Appetizers" },
    { key: "breakfast", label: "Breakfast" },
    { key: "desserts", label: "Desserts" },
    { key: "beverages", label: "Beverages" },
    { key: "side_dishes", label: "Side_Dishes" },
    { key: "snacks", label: "Snacks" },
    { key: "soups", label: "Soups" },
    { key: "salads", label: "Salads" },
    { key: "vegetarian", label: "Vegetarian" },
    { key: "vegan", label: "Vegan" },
    { key: "gluten_free", label: "Gluten_Free" },
    { key: "seafood", label: "Seafood" },
    { key: "meat", label: "Meat" },
    { key: "poultry", label: "Poultry" },
    { key: "pasta", label: "Pasta" },
    { key: "rice_and_grains", label: "Rice" },
    { key: "baking", label: "Baking" },
    { key: "holiday", label: "Holiday" },
    { key: "international", label: "International" },
];